### ISSUE TITLE
"make distclean" removes Makefiles from project folder

### ISSUE THREAD

**Issue by jvalleroy** [matujo/mod_auth_env#4]
```
jvalleroy@debian:~/src/mod_auth_env$ make distclean
make[1]: Entering directory '/home/jvalleroy/src/mod_auth_env'
rm -f *.o *.lo *.slo *.obj *.a *.la  
rm -rf .libs
rm -f .deps Makefile modules.mk
make[1]: Leaving directory '/home/jvalleroy/src/mod_auth_env'
jvalleroy@debian:~/src/mod_auth_env$ ls
mod_auth_env.c
```

**Comment by jvalleroy** [comment]
Hmm, without the empty .deps file, "make distclean" just says:

```
jvalleroy@debian:~/src/mod_auth_env$ make distclean
/usr/share/apache2/build/rules.mk:236: .deps: No such file or directory
```

So maybe this is due to my .deps file being empty. (I'm not sure what's supposed to be in there.)

**Comment by gnoutchd** [comment]
I remember encountering this too during my packaging attempts. I vaguely remember tracking down the cause and coming the the conclusion that the build system created by apxs (?) sources a bunch of Apache-provided makefiles that will always delete `Makefile` when 'make distclean' is called.  I think the sourced makefiles all assume that they're part of an autotools buildsystem where `Makefile` et. al. are autogenerated with `./configure` and the like.

At that point I gave up and just hacked up my debian/rules to suppress the call to 'make distclean'.  A "proper" solution likely involves yet another bloody battle with the autotools.

**Comment by jvalleroy** [comment]
This should be fixed now.
